server:
  port: 8080

spring:
  application:
    name: projectPython
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectpythonmodel?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234